global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

accessLog: 
  format: json

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          permanent: false
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

providers:
  file:
    directory: "/etc/traefik.d/"
    watch: true
