http:
  middlewares:
    middle-strip-prefix:
      stripPrefix:
        prefixes:
          - "/s"

    middle-cors:
      headers:
        accessControlAllowOriginList: 
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "HEAD"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
          - "PATCH"
        accessControlAllowHeaders:
          - DNT
          - X-CustomHeader
          - Keep-Alive
          - User-Agent
          - X-Requested-With
          - If-Modified-Since
          - Cache-Control
          - Content-Type
          - Authorization

    middle-replace-uri-centrifugo:
      replacePath:
        path: "/connection/websocket"

    https-redirect-to-http:
      redirectScheme:
        scheme: http
        permanent: false

    http-redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: false