http:
  routers:
    route-golive:
      tls:
        certResolver: myresolver
      middlewares:
        - middle-cors
      entryPoints:
        - websecure
      service: service-golive
      # rule: Host("live.domain.com")
