http:
  routers:
    route-golive:
      rule: Host(`live.domain.com`)
      tls:
        certResolver: myresolver
      middlewares:
        - middle-cors
      entryPoints:
        - websecure
      service: service-golive
